import "stdlib/native";
import * as orm from "stdlib/orm";

function init() {
    orm.register({
        name: "userUpdate",
        permissionFlags: "CRUDI",
        label: "@@Actualización",
        pluralLabel: "@@Actualizaciones",
        properties: [
            { name: "idWorker", type: "lookup", refTable: "attendance:worker", refDesc: "name", label: "Trabajador" },
        ]
    })

    orm.register({
        name: "sync",
        permissionFlags: "CRUDI",
        label: "@@Sincronización",
        pluralLabel: "@@Sincronizaciones",
        properties: [
            { name: "idTerminal", type: "lookup", refTable: "attendance:terminal", refDesc: "name", label: "Terminal" },
            { name: "idUpdate", type: "lookup", refTable: "userUpdate", refDesc: "id", label: "Último cambio sincronizado" }
        ]
    })
}
//#region entities_autogenerated_do_not_edit

declare global {
	interface Sync {
		id?: number;
		idTerminal: number;
		terminalName?: string;
		idUpdate: number;
		updateId?: string;
		idCreateUser?: number;
		createUserName?: string;
		createDate?: time.Time;
		deleted?: boolean;
	}
	interface UserUpdate {
		id?: number;
		idWorker: number;
		workerName?: string;
		idCreateUser?: number;
		createUserName?: string;
		createDate?: time.Time;
		deleted?: boolean;
	}
}

//#endregion
