//#region entities_autogenerated_do_not_edit

namespace vallesyr{
	export interface Sync {
		id?: number;
		idTerminal: number;
		terminalName?: string;
		idUpdate: number;
		updateId?: string;
		idCreateUser?: number;
		createUserName?: string;
		createDate?: number | Date;
		deleted?: boolean;
	}
	export interface UserUpdate {
		id?: number;
		idWorker: number;
		workerName?: string;
		idCreateUser?: number;
		createUserName?: string;
		createDate?: number | Date;
		deleted?: boolean;
	}
}

//#endregion
